name: Basic CI

# This workflow runs on every push and pull request
on:
  push:
  pull_request:

jobs:
  basic-checks:
    name: Lint & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint:check
        continue-on-error: true
      
      - name: Run tests
        run: npm test