# cSpell:ignore mikestreety
name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'bin/**'
      - 'src/**'
      - 'prompts/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
      - 'README.md'
      - 'vitest.config.js'
      - 'eslint.config.js'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Update package.json version
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version
          
      - name: Publish to NPM
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release Summary
        run: |
          echo "## 📦 Published to NPM" >> $GITHUB_STEP_SUMMARY
          echo "- **Package**: [@mikestreety/ruck](https://www.npmjs.com/package/@mikestreety/ruck)" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Install**: `npm install -g @mikestreety/ruck`" >> $GITHUB_STEP_SUMMARY
          echo "- **Run**: `npx @mikestreety/ruck`" >> $GITHUB_STEP_SUMMARY